server:
  port: 9420
spring:
  datasource:
    druid:
      initialSize: 5
      maxActive: 20
      maxPoolPreparedStatementPerConnectionSize: 20
      maxWait: 60000
      minEvictableIdleTimeMillis: 300000
      minIdle: 5
      poolPreparedStatements: true
      testOnBorrow: false
      testOnReturn: false
      testWhileIdle: true
      timeBetweenEvictionRunsMillis: 60000
      validationQuery: show status like '%Service_Status%'
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/kaguya?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&rewriteBatchedStatements=TRUE&useAffectedRows=true&allowMultiQueries=true
    username: root
    password: kaguya

  redis:
    database: 0
    host: localhost
    port: 6379
    password:
    jedis:
      pool:
        max-active: 80
        max-idle: 30
        max-wait: 2000s
        min-idle: 10
  session:
    store-type: redis

  thymeleaf:
    cache: false
    check-template-location: true
    enabled: true
    encoding: UTF-8
    mode: HTML5
    suffix: .html
    servlet:
      content-type: text/html

# mybatis
mybatis:
  configuration:
    map-underscore-to-camel-case: true
  mapper-locations: classpath*:com/github/kaguya/**/xml/*Mapper.xml
mapper:
  identity: MYSQL
  mappers: ''
  not-empty: false
pagehelper:
  helper-dialect: mysql
  params: count=countSql
  reasonable: true
  support-methods-arguments: true

# kaguya
kaguaya:
  system:
    config:
      author: AkaneMurakawa
      email: test@gmail.com
      host: http://localhost:9420

# just auth
justauth:
  enabled: true
  type:
    github:
      client-id: 5c2711630ff813639351
      client-secret: b5101b988548765eaff6577e2c77f71c7c383be9
      redirect-uri: http://localhost:9420/oauth/github/callback
  cache:
    type: redis
    prefix: 'SOCIAL::STATE::'
    timeout: 1h